/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingredients */
        get: operations["list_ingredients_api_catalog_ingredients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/ingredients/{ingredient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredient */
        get: operations["get_ingredient_api_catalog_ingredients__ingredient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Ingredient */
        patch: operations["patch_ingredient_api_catalog_ingredients__ingredient_id__patch"];
        trace?: never;
    };
    "/api/catalog/ingredients/{ingredient_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Ingredient */
        post: operations["merge_ingredient_api_catalog_ingredients__ingredient_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collections */
        get: operations["list_collections_api_collections_get"];
        put?: never;
        /** Create Collection */
        post: operations["create_collection_api_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Collection */
        delete: operations["delete_collection_api_collections__collection_id__delete"];
        options?: never;
        head?: never;
        /** Rename Collection */
        patch: operations["rename_collection_api_collections__collection_id__patch"];
        trace?: never;
    };
    "/api/files/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve File
         * @description Serve a stored file by its content-addressed ref.
         *
         *     Returns the raw bytes with a guessed media type.
         *     Invalid or missing refs produce a 404 envelope (no detail leaked).
         */
        get: operations["serve_file_api_files__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest File */
        post: operations["ingest_file_api_ingest_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Text */
        post: operations["ingest_text_api_ingest_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Url */
        post: operations["ingest_url_api_ingest_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/accept-high-confidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept High Confidence */
        post: operations["accept_high_confidence_api_jobs_accept_high_confidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/recipes/{recipe_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Draft */
        post: operations["accept_draft_api_jobs__job_id__recipes__recipe_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/recipes/{recipe_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Draft */
        post: operations["reject_draft_api_jobs__job_id__recipes__recipe_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_api_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_api_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        /** Update Recipe */
        patch: operations["update_recipe_api_recipes__recipe_id__patch"];
        trace?: never;
    };
    "/api/recipes/{recipe_id}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Recipe Collections
         * @description Full-replace the set of collections this recipe belongs to.
         *
         *     Returns the updated RecipeOut (rather than 204) so the client can render
         *     the new collection_ids without a follow-up GET.
         */
        put: operations["set_recipe_collections_api_recipes__recipe_id__collections_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Recipe Image */
        put: operations["upload_recipe_image_api_recipes__recipe_id__image_put"];
        post?: never;
        /** Delete Recipe Image */
        delete: operations["delete_recipe_image_api_recipes__recipe_id__image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/personal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Recipe Personal */
        patch: operations["update_recipe_personal_api_recipes__recipe_id__personal_patch"];
        trace?: never;
    };
    "/api/recipes/{recipe_id}/scaled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scale Recipe Endpoint */
        get: operations["scale_recipe_endpoint_api_recipes__recipe_id__scaled_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vocab */
        get: operations["get_vocab_api_vocab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasOut */
        AliasOut: {
            /** Alias */
            alias: string;
            /** Language */
            language: string;
        };
        /** Body_ingest_file_api_ingest_file_post */
        Body_ingest_file_api_ingest_file_post: {
            /** File */
            file: string;
        };
        /** Body_upload_recipe_image_api_recipes__recipe_id__image_put */
        Body_upload_recipe_image_api_recipes__recipe_id__image_put: {
            /** File */
            file: string;
        };
        /**
         * CollectionIn
         * @description Body for POST/PATCH /api/collections.
         */
        CollectionIn: {
            /** Name */
            name: string;
        };
        /**
         * CollectionOut
         * @description Response shape for the collections endpoints — includes a recipe count.
         *
         *     Not built via ``from_attributes`` off the ORM ``Collection`` directly
         *     (the count comes from a separate aggregate in the service layer), but
         *     ``from_attributes`` is still enabled so ``Collection.id``/``.name`` can
         *     be read off the ORM row when constructing this.
         */
        CollectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Recipe Count */
            recipe_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngredientGroupIn */
        IngredientGroupIn: {
            /** Lines */
            lines: components["schemas"]["IngredientLineIn"][];
            /** Name */
            name?: string | null;
        };
        /** IngredientGroupOut */
        IngredientGroupOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["IngredientLineOut"][];
            /** Name */
            name?: string | null;
        };
        /** IngredientLineIn */
        IngredientLineIn: {
            /**
             * Is Optional
             * @default false
             */
            is_optional: boolean;
            /** Name */
            name?: string | null;
            /** Note */
            note?: string | null;
            /** Original Text */
            original_text: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit */
            unit?: string | null;
        };
        /** IngredientLineOut */
        IngredientLineOut: {
            /** Canonical Ingredient Id */
            canonical_ingredient_id?: string | null;
            /** Display */
            readonly display: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Approx
             * @default false
             */
            is_approx: boolean;
            /**
             * Is Optional
             * @default false
             */
            is_optional: boolean;
            /** Name */
            name?: string | null;
            /** Normalized Amount */
            normalized_amount?: number | null;
            /** Normalized Unit */
            normalized_unit?: string | null;
            /** Note */
            note?: string | null;
            /** Original Text */
            original_text: string;
            /** Quantity */
            quantity?: number | null;
            /** Unit */
            unit?: string | null;
        };
        /** IngredientOut */
        IngredientOut: {
            /** Aliases */
            aliases: components["schemas"]["AliasOut"][];
            /** Category */
            category: string;
            /** Density G Per Ml */
            density_g_per_ml: number | null;
            /** Dietary Flags */
            dietary_flags: string[];
            /** Gram Weights */
            gram_weights: {
                [key: string]: number;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            preferred_measure: components["schemas"]["PreferredMeasure"];
            status: components["schemas"]["IngredientStatus"];
        };
        /** IngredientPatch */
        IngredientPatch: {
            /** Category */
            category?: string | null;
            /** Density G Per Ml */
            density_g_per_ml?: number | null;
            /** Dietary Flags */
            dietary_flags?: string[] | null;
            /** Gram Weights */
            gram_weights?: {
                [key: string]: number;
            } | null;
            /** Name */
            name?: string | null;
            preferred_measure?: components["schemas"]["PreferredMeasure"] | null;
            status?: components["schemas"]["IngredientStatus"] | null;
        };
        /**
         * IngredientStatus
         * @enum {string}
         */
        IngredientStatus: "seeded" | "unreviewed" | "reviewed";
        /**
         * InputType
         * @enum {string}
         */
        InputType: "url" | "pdf" | "image" | "text";
        /**
         * JobDetailOut
         * @description Extended job output that also embeds the list of draft recipe summaries.
         */
        JobDetailOut: {
            /**
             * Artifacts
             * @default {}
             */
            artifacts: {
                [key: string]: string;
            };
            /** Attempts */
            attempts: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Drafts
             * @default []
             */
            drafts: components["schemas"]["RecipeSummary"][];
            /** Error */
            error?: string | null;
            /** Extraction Meta */
            extraction_meta?: {
                [key: string]: unknown;
            } | null;
            /** Filename */
            filename?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            input_type: components["schemas"]["InputType"];
            /**
             * Produced Recipe Ids
             * @default []
             */
            produced_recipe_ids: string[];
            /** Reason */
            reason?: string | null;
            status: components["schemas"]["JobStatus"];
            /** Text Preview */
            text_preview?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * JobOut
         * @description Serialisable representation of a Job row.
         *
         *     ``source_fingerprint`` is intentionally EXCLUDED (internal implementation
         *     detail — do not expose to clients).
         *
         *     ``url``, ``filename``, and ``text_preview`` are derived from *payload*
         *     at validation time (never the full raw payload).
         *
         *     ``artifacts`` maps store keys to /api/files/{ref} URL paths.
         *     ``cost_usd`` is exposed as ``float`` for JSON friendliness.
         */
        JobOut: {
            /**
             * Artifacts
             * @default {}
             */
            artifacts: {
                [key: string]: string;
            };
            /** Attempts */
            attempts: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Extraction Meta */
            extraction_meta?: {
                [key: string]: unknown;
            } | null;
            /** Filename */
            filename?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            input_type: components["schemas"]["InputType"];
            /**
             * Produced Recipe Ids
             * @default []
             */
            produced_recipe_ids: string[];
            /** Reason */
            reason?: string | null;
            status: components["schemas"]["JobStatus"];
            /** Text Preview */
            text_preview?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "needs_review" | "done" | "failed" | "not_a_recipe";
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MergeIn */
        MergeIn: {
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
        };
        /**
         * PreferredMeasure
         * @enum {string}
         */
        PreferredMeasure: "mass" | "volume";
        /** RecipeIn */
        RecipeIn: {
            /** Cook Min */
            cook_min?: number | null;
            /**
             * Cuisines
             * @default []
             */
            cuisines: string[];
            /** Description */
            description?: string | null;
            /**
             * Dish Types
             * @default []
             */
            dish_types: string[];
            /** Groups */
            groups: components["schemas"]["IngredientGroupIn"][];
            /**
             * Language
             * @default en
             */
            language: string;
            /** Prep Min */
            prep_min?: number | null;
            servings?: components["schemas"]["ServingsIn"] | null;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepIn"][];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Title */
            title: string;
            /** Total Min */
            total_min?: number | null;
        };
        /** RecipeOut */
        RecipeOut: {
            /**
             * Collection Ids
             * @default []
             */
            collection_ids: string[];
            /** Cook Min */
            cook_min?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Cuisines
             * @default []
             */
            cuisines: string[];
            /** Derived From */
            derived_from?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Dish Types
             * @default []
             */
            dish_types: string[];
            /** Extraction Meta */
            extraction_meta?: {
                [key: string]: unknown;
            } | null;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["IngredientGroupOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Ref */
            image_ref?: string | null;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Last Edited At */
            last_edited_at?: string | null;
            /** Last Edited By */
            last_edited_by?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Prep Min */
            prep_min?: number | null;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            readonly servings: components["schemas"]["ServingsOut"] | null;
            /** Source */
            source?: string | null;
            /** Source Type */
            source_type: string;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepOut"][];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Title */
            title: string;
            /** Total Min */
            total_min?: number | null;
        };
        /**
         * RecipePage
         * @description Paginated result of ``GET /api/recipes``.
         */
        RecipePage: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RecipePersonalPatch
         * @description Lightweight patch for personal metadata (favorites/notes).
         *
         *     Distinct from RecipeIn: does not trigger the full destructive-replace
         *     semantics of PATCH /api/recipes/{id}. ``notes`` uses model_fields_set at
         *     the router layer to distinguish "field absent" from "explicit null".
         */
        RecipePersonalPatch: {
            /** Is Favorite */
            is_favorite?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** RecipeSummary */
        RecipeSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Dish Types
             * @default []
             */
            dish_types: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Ref */
            image_ref?: string | null;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Title */
            title: string;
            /** Total Min */
            total_min?: number | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ScaledGroupOut
         * @description A scaled ingredient group.
         */
        ScaledGroupOut: {
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["ScaledLineOut"][];
            /** Name */
            name?: string | null;
        };
        /**
         * ScaledLineOut
         * @description A single scaled ingredient line.
         */
        ScaledLineOut: {
            /** Display */
            display: string;
            /**
             * Is Approx
             * @default false
             */
            is_approx: boolean;
            /**
             * Is Optional
             * @default false
             */
            is_optional: boolean;
            /** Normalized Amount */
            normalized_amount?: number | null;
            /** Normalized Unit */
            normalized_unit?: string | null;
            /** Note */
            note?: string | null;
            /** Original Text */
            original_text: string;
            /**
             * Passes Through
             * @default false
             */
            passes_through: boolean;
            /** Quantity Display */
            quantity_display?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /**
         * ScaledRecipeOut
         * @description Result of scaling a recipe by a factor.
         */
        ScaledRecipeOut: {
            /** Factor */
            factor: number;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["ScaledGroupOut"][];
            /**
             * Recipe Id
             * Format: uuid
             */
            recipe_id: string;
            servings?: components["schemas"]["ServingsOut"] | null;
            /**
             * Step Text Disclaimer
             * @default true
             */
            step_text_disclaimer: boolean;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepOut"][];
        };
        /** ServingsIn */
        ServingsIn: {
            /** Amount */
            amount?: number | null;
            /** Unit Text */
            unit_text?: string | null;
        };
        /** ServingsOut */
        ServingsOut: {
            /** Amount */
            amount?: number | null;
            /** Unit Text */
            unit_text?: string | null;
        };
        /**
         * SetRecipeCollectionsIn
         * @description Body for PUT /api/recipes/{recipe_id}/collections — full-replace semantics.
         */
        SetRecipeCollectionsIn: {
            /**
             * Collection Ids
             * @default []
             */
            collection_ids: string[];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "web" | "pdf" | "image" | "text" | "manual";
        /** StepIn */
        StepIn: {
            /** Original Text */
            original_text: string;
        };
        /** StepOut */
        StepOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ingredient Line Refs
             * @default []
             */
            ingredient_line_refs: string[];
            /** Original Text */
            original_text: string;
        };
        /** SubmitTextIn */
        SubmitTextIn: {
            /** Text */
            text: string;
        };
        /** SubmitUrlIn */
        SubmitUrlIn: {
            /** Url */
            url: string;
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingredients_api_catalog_ingredients_get: {
        parameters: {
            query?: {
                q?: string;
                status?: components["schemas"]["IngredientStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredient_api_catalog_ingredients__ingredient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_ingredient_api_catalog_ingredients__ingredient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_ingredient_api_catalog_ingredients__ingredient_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_api_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"][];
                };
            };
        };
    };
    create_collection_api_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_api_collections__collection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_collection_api_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_file_api_files__ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_file_api_ingest_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_file_api_ingest_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_text_api_ingest_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_url_api_ingest_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_high_confidence_api_jobs_accept_high_confidence_post: {
        parameters: {
            query?: {
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_draft_api_jobs__job_id__recipes__recipe_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_draft_api_jobs__job_id__recipes__recipe_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_recipes_get: {
        parameters: {
            query?: {
                q?: string | null;
                cuisine?: string | null;
                dish_type?: string | null;
                tag?: string | null;
                dietary?: ("vegan" | "vegetarian" | "gluten_free") | null;
                max_total_min?: number | null;
                source_type?: components["schemas"]["SourceType"] | null;
                favorites?: boolean | null;
                collection?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_api_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_api_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_api_recipes__recipe_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_recipe_collections_api_recipes__recipe_id__collections_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRecipeCollectionsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_recipe_image_api_recipes__recipe_id__image_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_recipe_image_api_recipes__recipe_id__image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_image_api_recipes__recipe_id__image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_personal_api_recipes__recipe_id__personal_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipePersonalPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scale_recipe_endpoint_api_recipes__recipe_id__scaled_get: {
        parameters: {
            query?: {
                factor?: number | null;
                target_servings?: number | null;
            };
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaledRecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vocab_api_vocab_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
}
