"""catalog tables

Revision ID: 2852359280fc
Revises: de5a519148bd
Create Date: 2026-06-12 17:54:56.366444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2852359280fc"
down_revision: str | Sequence[str] | None = "de5a519148bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "preferred_measure",
            sa.Enum("mass", "volume", name="preferredmeasure"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("seeded", "unreviewed", "reviewed", name="ingredientstatus"),
            nullable=False,
        ),
        sa.Column(
            "dietary_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("density_g_per_ml", sa.Float(), nullable=True),
        sa.Column(
            "gram_weights",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["canonical_ingredients.id"],
            name=op.f("fk_canonical_ingredients_merged_into_id_canonical_ingredients"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_ingredients")),
    )
    op.create_index(
        op.f("ix_canonical_ingredients_name"),
        "canonical_ingredients",
        ["name"],
        unique=True,
    )
    op.create_table(
        "ingredient_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["canonical_ingredients.id"],
            name=op.f("fk_ingredient_aliases_ingredient_id_canonical_ingredients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredient_aliases")),
    )
    op.create_index(
        op.f("ix_ingredient_aliases_alias"),
        "ingredient_aliases",
        ["alias"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingredient_aliases_ingredient_id"),
        "ingredient_aliases",
        ["ingredient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ingredient_aliases_ingredient_id"),
        table_name="ingredient_aliases",
    )
    op.drop_index(
        op.f("ix_ingredient_aliases_alias"),
        table_name="ingredient_aliases",
    )
    op.drop_table("ingredient_aliases")
    op.drop_index(
        op.f("ix_canonical_ingredients_name"),
        table_name="canonical_ingredients",
    )
    op.drop_table("canonical_ingredients")
    # ### end Alembic commands ###
