"""ingestion jobs table

Revision ID: 6ce5046fad00
Revises: 2751f1c43b33
Create Date: 2026-06-13 00:07:16.607564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ce5046fad00"
down_revision: str | Sequence[str] | None = "2751f1c43b33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "input_type", sa.Enum("url", "pdf", "image", "text", name="inputtype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "needs_review",
                "done",
                "failed",
                "not_a_recipe",
                name="jobstatus",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extraction_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("produced_recipe_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_jobs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_queue_poll", "jobs", ["status", "next_attempt_at"], unique=False)
    op.create_index(
        op.f("ix_jobs_source_fingerprint"), "jobs", ["source_fingerprint"], unique=False
    )
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source_fingerprint"), table_name="jobs")
    op.drop_index("ix_jobs_queue_poll", table_name="jobs")
    op.drop_table("jobs")
    sa.Enum(name="jobstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="inputtype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
