"""recipe favorites and notes

Revision ID: 7b5f9497c55f
Revises: c8e5b811e6e3
Create Date: 2026-07-08 19:42:58.917716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b5f9497c55f"
down_revision: str | Sequence[str] | None = "c8e5b811e6e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column("is_favorite", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("recipes", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "notes")
    op.drop_column("recipes", "is_favorite")
    # ### end Alembic commands ###
