"""cookbook tables

Revision ID: ffb0e42d55c6
Revises: 2852359280fc
Create Date: 2026-06-12 19:19:41.499225

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffb0e42d55c6"
down_revision: str | Sequence[str] | None = "2852359280fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cuisines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuisines")),
        sa.UniqueConstraint("name", name=op.f("uq_cuisines_name")),
    )
    op.create_table(
        "dish_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dish_types")),
        sa.UniqueConstraint("name", name=op.f("uq_dish_types_name")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_ref", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=1000), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("web", "pdf", "image", "text", "manual", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=20), server_default="en", nullable=False),
        sa.Column("servings_amount", sa.Float(), nullable=True),
        sa.Column("servings_unit_text", sa.String(length=100), nullable=True),
        sa.Column("prep_min", sa.Integer(), nullable=True),
        sa.Column("cook_min", sa.Integer(), nullable=True),
        sa.Column("total_min", sa.Integer(), nullable=True),
        sa.Column("extraction_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("derived_from", sa.Uuid(), nullable=True),
        sa.Column("last_edited_by", sa.Uuid(), nullable=True),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["derived_from"],
            ["recipes.id"],
            name=op.f("fk_recipes_derived_from_recipes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_edited_by"],
            ["users.id"],
            name=op.f("fk_recipes_last_edited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_recipes_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    op.create_index(op.f("ix_recipes_owner_id"), "recipes", ["owner_id"], unique=False)
    op.create_index(
        "uq_recipes_owner_fingerprint",
        "recipes",
        ["owner_id", "source_fingerprint"],
        unique=True,
        postgresql_where="source_fingerprint IS NOT NULL",
    )
    op.create_table(
        "ingredient_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_ingredient_groups_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredient_groups")),
    )
    op.create_index(
        op.f("ix_ingredient_groups_recipe_id"), "ingredient_groups", ["recipe_id"], unique=False
    )
    op.create_table(
        "recipe_cuisines",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("cuisine_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cuisine_id"],
            ["cuisines.id"],
            name=op.f("fk_recipe_cuisines_cuisine_id_cuisines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_cuisines_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", "cuisine_id", name=op.f("pk_recipe_cuisines")),
    )
    op.create_table(
        "recipe_dish_types",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("dish_type_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dish_type_id"],
            ["dish_types.id"],
            name=op.f("fk_recipe_dish_types_dish_type_id_dish_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_dish_types_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", "dish_type_id", name=op.f("pk_recipe_dish_types")),
    )
    op.create_table(
        "recipe_tags",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_tags_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_recipe_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("recipe_id", "tag_id", name=op.f("pk_recipe_tags")),
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column(
            "ingredient_line_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_steps_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_steps")),
    )
    op.create_index(op.f("ix_steps_recipe_id"), "steps", ["recipe_id"], unique=False)
    op.create_table(
        "ingredient_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("canonical_ingredient_id", sa.Uuid(), nullable=True),
        sa.Column("normalized_amount", sa.Float(), nullable=True),
        sa.Column("normalized_unit", sa.String(length=10), nullable=True),
        sa.Column("is_approx", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("is_optional", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_ingredient_id"],
            ["canonical_ingredients.id"],
            name=op.f("fk_ingredient_lines_canonical_ingredient_id_canonical_ingredients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["ingredient_groups.id"],
            name=op.f("fk_ingredient_lines_group_id_ingredient_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredient_lines")),
    )
    op.create_index(
        op.f("ix_ingredient_lines_canonical_ingredient_id"),
        "ingredient_lines",
        ["canonical_ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingredient_lines_group_id"), "ingredient_lines", ["group_id"], unique=False
    )
    # ### end Alembic commands ###

    # Seed dish_types vocab (spec: includes drinks)
    dish_types_table = sa.table(
        "dish_types",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
    )
    op.bulk_insert(
        dish_types_table,
        [
            {"id": uuid.uuid4(), "name": "cocktail"},
            {"id": uuid.uuid4(), "name": "drink"},
            {"id": uuid.uuid4(), "name": "smoothie"},
            {"id": uuid.uuid4(), "name": "main"},
            {"id": uuid.uuid4(), "name": "dessert"},
            {"id": uuid.uuid4(), "name": "side"},
            {"id": uuid.uuid4(), "name": "breakfast"},
            {"id": uuid.uuid4(), "name": "soup"},
            {"id": uuid.uuid4(), "name": "salad"},
            {"id": uuid.uuid4(), "name": "bread"},
            {"id": uuid.uuid4(), "name": "sauce"},
            {"id": uuid.uuid4(), "name": "snack"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingredient_lines_group_id"), table_name="ingredient_lines")
    op.drop_index(
        op.f("ix_ingredient_lines_canonical_ingredient_id"), table_name="ingredient_lines"
    )
    op.drop_table("ingredient_lines")
    op.drop_index(op.f("ix_steps_recipe_id"), table_name="steps")
    op.drop_table("steps")
    op.drop_table("recipe_tags")
    op.drop_table("recipe_dish_types")
    op.drop_table("recipe_cuisines")
    op.drop_index(op.f("ix_ingredient_groups_recipe_id"), table_name="ingredient_groups")
    op.drop_table("ingredient_groups")
    op.drop_index(
        "uq_recipes_owner_fingerprint",
        table_name="recipes",
        postgresql_where="source_fingerprint IS NOT NULL",
    )
    op.drop_index(op.f("ix_recipes_owner_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_table("tags")
    op.drop_table("dish_types")
    op.drop_table("cuisines")
    # Drop the native PG enum type created by upgrade
    sa.Enum(name="sourcetype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
